# Generated by Django 5.0.6 on 2024-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='instrumentos'),
        ),
    ]
